# ***Intro to ML1***

## ***Wprowadzenie***

W tym notatniku przedstawię przykładową implementację metod opisanych podczas wykładu przy użyciu zaprojektowanych w tym celu popularnych bibliotek języka Python.

Omówiona zostanie regresja i klasyfikacja, a także zaimplementowane i dostępne w gotowych bibliotekach metody przeznaczone do tworzenia i treningu modeli uczenia maszynowego. 

## ***Wykorzystywane biblioteki***

**Numpy** - to biblioteka programistyczna dla języka Python, dodająca obsługę dużych, wielowymiarowych tabel i macierzy.

**Scikit-learn** - Scikit-learn to bezpłatna biblioteka do uczenia maszynowego języka programowania Python. Zawiera różne algorytmy klasyfikacji, regresji a także metody pozwalające na automatyzację przebiegu treningu modeli.

## ***Regresja***
Celem regresji jest predykcja dla podanych danych wartości ciągłych lub uporządkowanych czyli wartości z dziedziny liczb rzeczywistych.

Przykładem regresji może być predykcja cen laptopów, cen mieszkań na rynku czy poziomu cukru we krwi.

### ***Dane***
Najpierw przygotujmy proste dane uczące.

Będą to dane reprezentujące parametry poszczególnych laptopów (jako macierz X) i ich ceny (wektor etykiet y).

In [ ]:
# import biblioteki numpy
import numpy as np

# Nasze dane jako wektory 4 wartości = [RAM, GPU VRAM, liczba rdzeni CPU, taktowanie CPU]
data = np.array([[8., 0., 4., 2.4],
        [16., 6., 8., 2.5],
        [8., 2., 8., 2.3],
        [16., 8., 8., 3.0],
        [32., 12., 16., 3.8]])

# Nasze etykiety - ceny poszczególnych laptopów
prices = np.array([1500., 3000., 1900., 5000., 11000.])

# Szybki podgląd całości danych
print(data)
print(prices)

[[ 8.   0.   4.   2.4]
 [16.   6.   8.   2.5]
 [ 8.   2.   8.   2.3]
 [16.   8.   8.   3. ]
 [32.  12.  16.   3.8]]
[ 1500.  3000.  1900.  5000. 11000.]


### ***Hipoteza***

Poniżej zaimplementujemy hipotezę czyli funkcję za pomocą której nasz 'model' będzie wyliczał ceny dla nowych danych, które otrzyma na wejściu.

Hipoteza ma postać h(x) = a*x4 + b*x3 + c*x2 + d*x1 + e

Model uczy się na danych zmieniając wartość swoich parametrów, które zawarte są w wektorze theta.

In [ ]:
# wektor parametrów hipotezy theta [a, b, c, d, e]
theta = [100, 150, 200, 100]

# hipoteza h(x) = a*x4 + b*x3 + c*x2 + d*x1 + e
vector_h = []

# obliczenie hipotezy dla każdego przykładu danych
for x in data:
    h = theta[0] * x[3] + theta[1] * x[2] + theta[2] * x[1] + theta[1] * x[0] + theta[0]
    vector_h.append(h)

print(vector_h)

[2140.0, 5150.0, 3130.0, 5600.0, 10080.0]


### ***Funkcja kosztu***

Nasza funkcja kosztu to tak zwany MSE (*ang. Mean Squared Error*) czyli funkcja *błędu średniokwadratowego*.

Wzór tej funkcji jest następujący:

L(y, y_pred) = 1/n * sum((y - y_pred)^2)

In [ ]:
# Funckja kosztu L = 1/n * sum((y - y_pred)^2)
L = np.sum(np.power(prices - vector_h, 2)) / prices.shape[0]

# wyświetlamy wartość naszej funkcji kosztu
print(L)

1550280.0


### ***Metoda gradientu prostego***

TODO


In [ ]:
optimize = np.power(prices - vector_h, 2) / prices.shape[0]
gradient = np.gradient(optimize)
print(optimize)
print(gradient)

[ 81920. 924500. 302580.  72000. 169280.]
[ 842580.  110330. -426250.  -66650.   97280.]


### ***Przykład z użyciem gotowych danych i funkcji***
W praktyce nie ma sensu zawsze implementować powyższych funkcji na nowo. Zamiast z tego korzysta się z już gotowych implementacji, dostępnych w bilbiotekach danego języka programowania.
W tym notatniku przedstawię funkcje z biblioteki [scikit-learn](https://scikit-learn.org/stable/index.html), odpowiadające za tworzenie modeli, podział zbiorów danych czy uczenie tych modeli.

Biblioteka ta udostępnia również gotowe zbiory danych, zarówno do regresji jak i klasufikacji, na których mozna przeprowadzać testy opracowywanych algorytmów: https://scikit-learn.org/stable/datasets/toy_dataset.html.

W przypadku regresji skorzystamy ze zbioru diabetes

In [ ]:
from sklearn.datasets import load_diabetes

# Załadujmy zbiór w celu wyświetlenia listy parametrów służących do opisu danych 
diabetes = load_diabetes()
print(diabetes.feature_names)

# W celu łatwiejszej pracy z danymi korzystamy z parametru return_X_y, który
# zwraca nam nam dane w postaci macierzy X i wektor etykiet y
X, y = load_diabetes(return_X_y=True)

# wyświetlmy rozmiar danych, a także przykładowe wartości
print(X.shape)
print(y.shape)
print(X[0])
print(y[0])

(442, 10)
(442,)
[ 0.03807591  0.05068012  0.06169621  0.02187235 -0.0442235  -0.03482076
 -0.04340085 -0.00259226  0.01990842 -0.01764613]
151.0


Jako model wykorzystamy model SGD (*ang. Stochastic Gradient Descent*) [link](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.SGDRegressor.html) czyli model wykorzystujący odmianę metody gradientu prostego do wyliczania wartości y_pred. 

In [ ]:
from sklearn.linear_model import SGDRegressor

model = SGDRegressor(max_iter=1000, tol=1e-3)
# wyświetlamy utworzony model w celu podglądu parametrów
print(model)

SGDRegressor(alpha=0.0001, average=False, early_stopping=False, epsilon=0.1,
             eta0=0.01, fit_intercept=True, l1_ratio=0.15,
             learning_rate='invscaling', loss='squared_loss', max_iter=1000,
             n_iter_no_change=5, penalty='l2', power_t=0.25, random_state=None,
             shuffle=True, tol=0.001, validation_fraction=0.1, verbose=0,
             warm_start=False)


W tej komórce wykorzystamy wbudowaną funkcję [train_test_split](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html) pozwalającą na automatyzację procesu podziału zbioru na dane treningowe i testowe.

Do określenia skuteczności modelu wykorzystany właśnie funkcję MSE.

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

# podział zbioru na zbiór treningowy i testowy
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=42)

# trening modelu na zbiorze treningowym
model.fit(X_train, y_train)

# test modelu na zbiorze testowym
y_pr = model.predict(X_test)

print(y_test[0])
print(y_pr[0])

# obliczenie i wyświetlenie wartości funkcji kosztu
print(mean_squared_error(y_test, y_pr))

219.0
164.3739228754339
3111.467828467563


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_stochastic_gradient.py:1187: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)


W tym miejscu przedstawię metodę treningu typu cross-validation. W skrócie metoda ta polega na określenie na ile grup dzielimy zbiór danych treningowych (najczęściej jest to 5) i następnie jedną z tych grup wybieramy jako zbiór walidacyjny pozostałe jako zbiór treningowy.

Cały proces polega na treningu modelu na zbiorze treningowym i jego walidacji (ocenie skuteczności) na zbiorze walidacyjnym.
Proces ten jest powtarzany n razy, gdzie n oznacza na ile grup dzielimy nasze dane. W kazdym kroku wybierana jest inna grupa danych jako zbiór walidacyjny.
Po więcej informacji zapraszam do dokumentacji: [link](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.StratifiedKFold.html#sklearn.model_selection.StratifiedKFold)

In [ ]:
from sklearn.model_selection import StratifiedKFold

# Tworzymy obiekt klasy StratifiedKFold
skf = StratifiedKFold(n_splits=5)

# Tworzymy dwie listy na modele tworzone dla każdego kroku oraz na funkcję kosztu
# wyliczoną na zbiorze walidacyjnym
models = []
errors = []

# Główna pętla, metoda split odpowiada za proces kross-walidacji
for train_index, val_index in skf.split(X_train, y_train):
    model = SGDRegressor(max_iter=10000, tol=1e-3)
    X_tr, y_tr = X_train[train_index], y_train[train_index]
    X_val, y_val = X_train[val_index], y_train[val_index]

    # Trening modelu
    model.fit(X_tr, y_tr)
    # Predykcja etykiet dla danych walidacyjnych
    y_pr = model.predict(X_val)

    # Obliczenie funkcji kosztu MSE dla danego kroku
    errors.append(mean_squared_error(y_val, y_pr))
    models.append(model)

# Pobranie kroku, dla którego wartość funkcji kosztu była najmniejsza
best_error_idx = np.argmin(errors)

# Wybór tego modelu i błędu
best_error = errors[best_error_idx]
best_model = models[best_error_idx]

print("\n")
print("\n")

# Test najlepszego modelu na zbiorze testowym
y_pr = best_model.predict(X_test)
test_error = mean_squared_error(y_test, y_pr)

print("Najniższy błąd modelu na zbiorze walidacyjnym {}", best_error)
print("Błąd modelu na zbiorze testowym {}", test_error)    

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:667: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)






[2606.734646298559, 3440.575519952246, 4175.912917226848, 2953.882798167365, 2316.6481970073414]




Najniższy błąd modelu na zbiorze walidacyjnym {} 2316.6481970073414
Błąd modelu na zbiorze testowym {} 2828.142637582007


## ***Klasyfikacja***
Celem klasyfikacji jest z kolei predykcja wartości dyskretnych
Dla problemów klasyfikacji 

Tym razem wykorzystamy zbiór dany [iris](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_iris.html#sklearn.datasets.load_iris), przygotowany specjalnie dla algorytmów klasyfikacji.

In [ ]:
# Zaimportujmy zbiór danych przeznaczony do klasyfikacji
from sklearn.datasets import load_iris

iris = load_iris()

# Wyświetlmy parametry opisujące dane
print(iris.feature_names)

X, y = load_iris(return_X_y=True)


['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


Podobnie jak w przypadku regresji najpierw sprawdźmy 

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score
from sklearn.linear_model import SGDClassifier

model = SGDClassifier()
# podział zbioru na zbiór treningowy i testowy
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=42)

# trening modelu na zbiorze treningowym
model.fit(X_train, y_train)

# test modelu na zbiorze testowym
y_pr = model.predict(X_test)

print(y_test[0])
print(y_pr[0])

# obliczenie i wyświetlenie wartości funkcji kosztu
print(accuracy_score(y_test, y_pr))
print(f1_score(y_test, y_pr, average='micro'))

1
2
0.7
0.7


### Hipoteza - funkcja logiczna

### Funkcja kosztu